version: '3'

# Define services
services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
  
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
        
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    client:
      image: yandex/clickhouse-client
      command: ['--host', 'server']

  swe:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    depends_on:
      - nats